version: '3.8'

services:
  wg0-obfuscator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.wg0-obfuscator.conf:/etc/wg0-obfuscator/wg0-obfuscator.conf
    ports:
      - "13255:13255/udp"
    container_name: wg0-obfuscator-container
    restart: unless-stopped
