#!/bin/sh
# LuCI defaults for WireGuard Obfuscator
# Copyright (C) 2024-2025 Alexey Cluster <cluster@cluster.wtf>
# Licensed under GPLv3

# Ensure wg-obfuscator UCI configuration exists
if ! uci -q show wg-obfuscator >/dev/null 2>&1; then
    # Create default UCI configuration if it doesn't exist
    uci -q batch <<EOF
set wg-obfuscator.main=wg_obfuscator
set wg-obfuscator.main.enabled='0'
set wg-obfuscator.main.source_lport='13255'
set wg-obfuscator.main.target='10.13.1.100:13255'
set wg-obfuscator.main.key='test'
set wg-obfuscator.main.source_if='0.0.0.0'
set wg-obfuscator.main.masking='AUTO'
set wg-obfuscator.main.verbose='INFO'
set wg-obfuscator.main.max_clients='1024'
set wg-obfuscator.main.idle_timeout='300'
set wg-obfuscator.main.max_dummy='4'
set wg-obfuscator.main.fwmark='0'
set wg-obfuscator.main.static_bindings=''
EOF
fi

# Commit changes
uci commit wg-obfuscator

exit 0