#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

PROG="/usr/bin/wg-obfuscator"
CONFIG="/etc/wg-obfuscator.conf"

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" -c "$CONFIG"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

reload_service() {
    stop
    start
}

service_triggers() {
    procd_add_reload_trigger "$CONFIG"
}