name: Publish Nightly Docker Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  IMAGE_NAME: wg-obfuscator
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/arm/v5,linux/386,linux/ppc64le,linux/s390x

jobs:
  public-nightly:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multiarch image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            clustermeerkat/${{ env.IMAGE_NAME }}:nightly
          platforms: ${{ env.PLATFORMS }}
          context: .
