name: Publish Nightly Docker Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: wg-obfuscator
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/arm/v5,linux/386,linux/ppc64le,linux/s390x

jobs:
  public-nightly:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute lowercase owner
        id: prep
        run: |
          OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')
          echo "owner=$OWNER_LC" >> $GITHUB_OUTPUT

      - name: Build and push multiarch image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ steps.prep.outputs.owner }}/${{ env.IMAGE_NAME }}:nightly
          platforms: ${{ env.PLATFORMS }}
          context: .
