#!/bin/sh
# WireGuard Obfuscator Configuration Generator
# This script generates wg-obfuscator.conf from UCI configuration

CONFIG_FILE="/etc/wg-obfuscator/wg-obfuscator.conf"
UCI_CONFIG="wg-obfuscator"

# Function to get UCI value with default
get_uci_value() {
    local section="$1"
    local option="$2"
    local default="$3"
    
    local value=$(uci -q get "${UCI_CONFIG}.${section}.${option}")
    if [ -z "$value" ]; then
        echo "$default"
    else
        echo "$value"
    fi
}

# Function to convert verbose level
convert_verbose_level() {
    case "$1" in
        "ERRORS") echo "0" ;;
        "WARNINGS") echo "1" ;;
        "INFO") echo "2" ;;
        "DEBUG") echo "3" ;;
        "TRACE") echo "4" ;;
        *) echo "2" ;;
    esac
}

# Function to generate config for a single instance
generate_instance_config() {
    local section="$1"
    local enabled=$(get_uci_value "$section" "enabled" "0")
    
    if [ "$enabled" = "0" ]; then
        return 0
    fi
    
    echo "[$section]"
    
    local source_if=$(get_uci_value "$section" "source_if" "0.0.0.0")
    if [ "$source_if" != "0.0.0.0" ]; then
        echo "source-if = $source_if"
    fi
    
    local source_lport=$(get_uci_value "$section" "source_lport" "13255")
    echo "source-lport = $source_lport"
    
    local target=$(get_uci_value "$section" "target" "10.13.1.100:13255")
    echo "target = $target"
    
    local key=$(get_uci_value "$section" "key" "test")
    echo "key = $key"
    
    local masking=$(get_uci_value "$section" "masking" "AUTO")
    echo "masking = $masking"
    
    local static_bindings=$(get_uci_value "$section" "static_bindings" "")
    if [ -n "$static_bindings" ]; then
        echo "static-bindings = $static_bindings"
    fi
    
    local verbose=$(get_uci_value "$section" "verbose" "INFO")
    local verbose_level=$(convert_verbose_level "$verbose")
    echo "verbose = $verbose_level"
    
    local max_clients=$(get_uci_value "$section" "max_clients" "1024")
    echo "max-clients = $max_clients"
    
    local idle_timeout=$(get_uci_value "$section" "idle_timeout" "300")
    echo "idle-timeout = $idle_timeout"
    
    local max_dummy_length_data=$(get_uci_value "$section" "max_dummy_length_data" "4")
    echo "max-dummy-length-data = $max_dummy_length_data"
    
    local fwmark=$(get_uci_value "$section" "fwmark" "0")
    if [ "$fwmark" != "0" ]; then
        echo "fwmark = $fwmark"
    fi
    
    echo ""
}

# Create config directory if it doesn't exist
mkdir -p "$(dirname "$CONFIG_FILE")"

# Check if UCI configuration exists before generating
sections=$(uci -q show "$UCI_CONFIG" | grep -o "^$UCI_CONFIG\.[^=]*" | cut -d. -f2 | sort -u)

if [ -z "$sections" ]; then
    echo "No UCI configuration found"
    exit 1
fi

# Generate configuration file
{
    echo "# WireGuard Obfuscator Configuration"
    echo "# Generated from UCI configuration on $(date)"
    echo "# Do not edit this file manually - use UCI instead"
    echo ""
    
    # Generate config for each section
    for section in $sections; do
        generate_instance_config "$section"
    done
} > "$CONFIG_FILE"

if [ $? -eq 0 ]; then
    echo "Configuration generated: $CONFIG_FILE"
else
    echo "Failed to generate configuration file"
    exit 1
fi